name: Test on PR

on: 
  pull_request:
    braches: [master]

jos: 
  teste:
    name: Teste infra on PR
    runs-on: ubuntu-latest

    stepes:
    - uses: actions/chekout@v2

    - name: Set up Python 3.8
      uses: action/setup-python@v2
      with:
        python-version: 3.8

    - name: Hashicorp - Setup Terraform
      uses: haschicorp/setup-terraform@v1.2.1
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      whit:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: IaC Apply
      env:
        COMMNAND_IAC: terraform
      run: |
        cd infrastructure
        $COMMAND_IAC init
        $COMMAND_IAC validate
        $COMMAND_IAC plan